### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by arilitan** [llanox/react-native-assets#1]
Thrilled you are building this library, I can't wait to use it. Please let me know if you plan on writing more detailed install instructions. I could not get this to build in my project, seems to have to do with the $(inherited flag)

**Comment by llanox** [comment]
Hi @arilitan, I'm working on it and I also working on create a npm module to be easier add to any project. The problem is that contains pods (native dependencies for AFNetworking library) I don't know how to do that yet. I found that  project https://github.com/ReactExtensionManager/rem; I still working on use that with this project. In the meantime, I'm going to add some  detailed install instructions and one example to you be able to use it :+1: 

Thanks,
Gabriel

**Comment by arilitan** [comment]
Awesome thank you! looking forward to trying it out.

**Comment by llanox** [comment]
@arilitan  Readme updated. Try again and let me know any suggestion or idea to improve it.
